/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cliente.pres.reservaciones;

import javax.swing.JOptionPane;

/**
 *
 * @author otzoy
 */
public class Android extends javax.swing.JInternalFrame {

    /**
     * Creates new form ABC
     */
    public Android() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtOrigen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbViajes = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnReservar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Reservaciones");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/res/location-delx24.png"))); // NOI18N
        setMinimumSize(new java.awt.Dimension(400, 300));
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        jPanel1Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel1.setLayout(jPanel1Layout);

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        jLabel1.setText("Código de origen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel1, gridBagConstraints);

        txtOrigen.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(txtOrigen, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        jLabel2.setText("Código de destino");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel2, gridBagConstraints);

        txtDestino.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(txtDestino, gridBagConstraints);

        btnGenerar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        btnGenerar.setText("Generar viajes");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(btnGenerar, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        jLabel3.setText("Viajes disponibles");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel3, gridBagConstraints);

        cmbViajes.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        cmbViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbViajesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(cmbViajes, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        jLabel4.setText("Costo total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        jLabel5.setText("Tiempo total");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel5, gridBagConstraints);

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1;
        jPanel1.add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        jPanel1.add(jSeparator1, gridBagConstraints);

        btnReservar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        btnReservar.setText("Reservar");
        btnReservar.setEnabled(false);
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(btnReservar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        //Valida el código de origen y destino
        Float origen = ValidarDecimal(this.txtOrigen.getText()),
                destino = ValidarDecimal(this.txtDestino.getText());
        //No es un numero
        if (origen == null) {
            JOptionPane.showMessageDialog(this, "El origen especificado no es un número entero", "Número inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //Es un número negativo
        if (origen < 0) {
            JOptionPane.showMessageDialog(this, "El origen especificado debe ser un número entero positivo", "Número inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //Lo mismo pero con el destino
        if (destino == null) {
            JOptionPane.showMessageDialog(this, "El destino especificado no es un número entero", "Número inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (destino < 0) {
            JOptionPane.showMessageDialog(this, "El destino especificado debe ser un número entero positivo", "Número inválido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //Realiza una llamada al webservice y recupera una lista de listas
        //Crea un arreglo de elementos
        //Habilita el botón reservar
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
        int r = JOptionPane.showConfirmDialog(this,
                String.format("Por favor revise los datos de la reservación:\n\tRuta: %s\n\tCosto: Q.%.2f\n Tiempo: %.2f min\n\n¿Desea crear la reservación con estos datos?"),
                "Reservación", JOptionPane.OK_CANCEL_OPTION & JOptionPane.INFORMATION_MESSAGE);
        if (r == JOptionPane.OK_OPTION) {
            //Intentará llamar al webservice para crear una reservación
            JOptionPane.showMessageDialog(this, "aea mongolazo");
        }
    }//GEN-LAST:event_btnReservarActionPerformed

    private void cmbViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbViajesActionPerformed
        // TODO add your handling code here:
        //Recupera el elemento actual que está siendo seleccionado el combo box
        //y luego coloca los datos de costo y tiempo en los labels correspondientes
    }//GEN-LAST:event_cmbViajesActionPerformed

    /**
     * Llena la lista con los elementos de los viajes
     * @param viajes 
     */
    private void llenarViajes(Elemento[] viajes){
        javax.swing.DefaultComboBoxModel a = new javax.swing.DefaultComboBoxModel();
        for(Elemento e : viajes){
            a.addElement(e);
        }
        this.cmbViajes.setModel(a);
    }
    
    /**
     * Clase interna que se utiliza para llenar un combo box
     */
    class Elemento{
        private final int id;
        private final String value;
        private final float costo, tiempo;

        public Elemento(int id, String value, float costo, float tiempo) {
            this.id = id;
            this.value = value;
            this.costo = costo;
            this.tiempo = tiempo;
        }

        public int getId() {
            return id;
        }

        public String getValue() {
            return value;
        }

        public float getCosto() {
            return costo;
        }

        public float getTiempo() {
            return tiempo;
        }
        
        @Override
        public String toString(){
            return value;
        }
    }
    
    /**
     * Convierte una cadena que represetna un número en un número
     *
     * @param cadena
     * @return un número decimal, {@code null} si no se pudo convertir
     */
    private Float ValidarDecimal(String cadena) {
        try {
            return Float.parseFloat(cadena);
        } catch (NumberFormatException e) {
            return null;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnReservar;
    private javax.swing.JComboBox<String> cmbViajes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtOrigen;
    // End of variables declaration//GEN-END:variables
}
