/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cliente.pres.reservaciones;

import java.awt.Frame;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author otzoy
 */
public class Carga extends javax.swing.JInternalFrame {

    private JFileChooser fch;
    private final Frame padre;

    /**
     * Creates new form Carga
     *
     * @param padre
     */
    public Carga(Frame padre) {
        initComponents();
        this.padre = padre;
        //Inicializa el selector de archivos
        this.fch = new JFileChooser();
        this.fch.setDialogTitle("Abrir...");
        FileNameExtensionFilter ExtensionFilter = new FileNameExtensionFilter("Archivo separado por comas CSV", new String[]{"csv", "CSV"});
        //Coloca un filtro para que solo permita abrir archivos CSV
        this.fch.setFileFilter(ExtensionFilter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnReserva = new javax.swing.JButton();

        setClosable(true);
        setTitle("Carga reservaciones");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/res/location.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(555, 90));
        setMinimumSize(new java.awt.Dimension(555, 90));
        setPreferredSize(new java.awt.Dimension(555, 90));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cargar reservaciones", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Microsoft Sans Serif", 0, 12))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Presiona aquí para seleccionar un archivo");
        jLabel1.setToolTipText("");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jLabel1, gridBagConstraints);

        btnReserva.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        btnReserva.setText("Cargar.");
        btnReserva.setToolTipText("");
        btnReserva.setEnabled(false);
        btnReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(btnReserva, gridBagConstraints);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if (this.fch.showOpenDialog(padre) == JFileChooser.APPROVE_OPTION) {
            this.jLabel1.setText(this.fch.getSelectedFile().getAbsolutePath());
            this.btnReserva.setEnabled(true);
        } else {
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void btnReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservaActionPerformed
        // TODO add your handling code here:
        //cargarReservacion(this.jLabel1.getText());
        this.jLabel1.setText("Presiona aquí para seleccionar un archivo");
        this.btnReserva.setEnabled(false);
    }//GEN-LAST:event_btnReservaActionPerformed

    /**
     * Carga las reservaciones del archivo seleccionado
     * @param URL 
     */
//    public void cargarReservacion(String URL) {
//        String l, csv[];
//        BufferedReader br = null;
//        try {
//            br = new BufferedReader(new InputStreamReader(new FileInputStream(new File(URL)), Charset.forName("UTF-8")));
//            while ((l = br.readLine()) != null) {
//                csv = l.split(",");
//                Lista<String> lviaje = new Lista();
//                int idReservacion = Integer.parseInt(csv[1]);
//                while (Proyecto2.th.existeLlave(idReservacion)) {
//                    idReservacion++;
//                }
//                for (int i = 4; i < csv.length; i++) {
//                    String n = Proyecto2.m.nombreDestino(Integer.parseInt(csv[i]));
//                    lviaje.agregarAlFinal(n != null ? n : "<CI>");
//                }
//                th.insertar(idReservacion, new Reservacion(csv[0], Float.valueOf(csv[2]), Float.valueOf(csv[3]), lviaje));
//            }
//        } catch (IOException | NumberFormatException ex) {
//            JOptionPane.showMessageDialog(padre, "Ocurrió un error al leer el archivo. Por favor verifique su sintaxis.", "Error", JOptionPane.ERROR_MESSAGE);
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(padre, ex.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
//        } finally {
//            try {
//                if (br != null) {
//                    br.close();
//                }
//            } catch (IOException ex) {
//            }
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReserva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
