/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cliente.pres.rutas;

import com.cliente.pres.Visor;
import java.util.Iterator;
import javax.swing.JDesktopPane;

/**
 *
 * @author otzoy
 */
public class EnRuta extends javax.swing.JInternalFrame {

    private final JDesktopPane padre;

    /**
     * Creates new form EnRuta
     *
     * @param padre
     */
    public EnRuta(JDesktopPane padre) {
        initComponents();
        this.padre = padre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVisualizar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        cmbOrigen = new javax.swing.JComboBox<>();
        cmbDestino = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Ruta en...");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/res/location-pinx24.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(200, 120));
        setMinimumSize(new java.awt.Dimension(200, 120));
        setPreferredSize(new java.awt.Dimension(200, 120));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        jLabel1.setText("Código Origen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 10)); // NOI18N
        jLabel2.setText("Código Destino");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel2, gridBagConstraints);

        btnVisualizar.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        btnVisualizar.setText("Visualizar");
        btnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 5, 0);
        jPanel1.add(btnVisualizar, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(jSeparator1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(cmbOrigen, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(cmbDestino, gridBagConstraints);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Instancia un nuevo {@code com.cliente.pres.Visor} para visualizar el reporte de una ruta
     * @param evt 
     */
    private void btnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarActionPerformed
        // TODO add your handling code here:
        //Recupera los codigo de los combo box list
        Integer origen = ((com.cliente.pres.Elemento)this.cmbOrigen.getSelectedItem()).getId(),
                destino = ((com.cliente.pres.Elemento)this.cmbDestino.getSelectedItem()).getId();
        //Ejecuta el webservice y recupera el string base64
        String base64 = reporteRutaEn(origen,destino);
        Visor i = new Visor(base64, String.format("Ruta de %s a %s", 
                ((com.cliente.pres.Elemento)this.cmbOrigen.getSelectedItem()).getValue(),
                ((com.cliente.pres.Elemento)this.cmbDestino.getSelectedItem())));
        padre.add(i);
        i.setVisible(true);
        i.pintar();
        this.dispose();
    }//GEN-LAST:event_btnVisualizarActionPerformed

    /**
     * Llena las listas con la información de los encabezados
     */
    public void llenarLista() {
        //Recupera la información de los encabezados
        java.util.List<String> viajes = recuperarEncabezados();
        String[] aux;
        javax.swing.DefaultComboBoxModel a = new javax.swing.DefaultComboBoxModel();
        javax.swing.DefaultComboBoxModel b = new javax.swing.DefaultComboBoxModel();
        for (String e : viajes) {
            aux = e.split(",");
            a.addElement(new com.cliente.pres.Elemento(Integer.parseInt(aux[0]), aux[1]));
            b.addElement(new com.cliente.pres.Elemento(Integer.parseInt(aux[0]), aux[1]));
        }
        this.cmbOrigen.setModel(a);
        this.cmbDestino.setModel(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisualizar;
    private javax.swing.JComboBox<String> cmbDestino;
    private javax.swing.JComboBox<String> cmbOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    /**
     * 
     * @return 
     */
    private static java.util.List<java.lang.String> recuperarEncabezados() {
        com.cliente.ws.ruta.RutaWS_Service service = new com.cliente.ws.ruta.RutaWS_Service();
        com.cliente.ws.ruta.RutaWS port = service.getRutaWSPort();
        return port.recuperarEncabezados();
    }

    /**
     * 
     * @param origen
     * @param destino
     * @return 
     */
    private static String reporteRutaEn(int origen, int destino) {
        com.cliente.ws.ruta.RutaWS_Service service = new com.cliente.ws.ruta.RutaWS_Service();
        com.cliente.ws.ruta.RutaWS port = service.getRutaWSPort();
        return port.reporteRutaEn(origen, destino);
    }
}
