/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.clienteedd.rutas;

import java.awt.Frame;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author otzoy
 */
public class Carga extends javax.swing.JInternalFrame {

    private JFileChooser fch;
    private final Frame padre;

    /**
     * Creates new form carga
     *
     * @param padre
     */
    public Carga(Frame padre) {
        initComponents();
        this.padre = padre;
        //Inicializa el selector de archivos
        this.fch = new JFileChooser();
        this.fch.setDialogTitle("Abrir...");
        FileNameExtensionFilter ExtensionFilter = new FileNameExtensionFilter("Archivo separado por comas CSV", new String[]{"csv", "CSV"});
        //Coloca un filtro para que solo permita abrir archivos CSV
        this.fch.setFileFilter(ExtensionFilter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDestino = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRuta = new javax.swing.JButton();

        setClosable(true);
        setTitle("Carga");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/res/route-dirx24.png"))); // NOI18N
        setMaximumSize(new java.awt.Dimension(555, 180));
        setMinimumSize(new java.awt.Dimension(555, 180));
        setPreferredSize(new java.awt.Dimension(555, 180));
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cargar destinos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Microsoft Sans Serif", 0, 12))); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Presiona aquí para seleccionar un archivo");
        jLabel1.setToolTipText("");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jLabel1, gridBagConstraints);

        btnDestino.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        btnDestino.setText("Cargar.");
        btnDestino.setToolTipText("");
        btnDestino.setEnabled(false);
        btnDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestinoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(btnDestino, gridBagConstraints);

        getContentPane().add(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cargar rutas", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Microsoft Sans Serif", 0, 12))); // NOI18N
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Presiona aquí para seleccionar un archivo");
        jLabel2.setToolTipText("");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        jPanel2.add(jLabel2, gridBagConstraints);

        btnRuta.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        btnRuta.setText("Cargar");
        btnRuta.setToolTipText("");
        btnRuta.setEnabled(false);
        btnRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel2.add(btnRuta, gridBagConstraints);

        getContentPane().add(jPanel2);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestinoActionPerformed
        // TODO add your handling code here:
        //cargarDestino(this.jLabel1.getText());
        this.jLabel1.setText("Presiona aquí para seleccionar un archivo");
        this.btnDestino.setEnabled(false);
    }//GEN-LAST:event_btnDestinoActionPerformed

    private void btnRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaActionPerformed
        // TODO add your handling code here:
        //cargarRuta(this.jLabel2.getText());
        this.jLabel2.setText("Presiona aquí para seleccionar un archivo");
        this.btnRuta.setEnabled(false);
    }//GEN-LAST:event_btnRutaActionPerformed

    /**
     * Depliega el selector de archivos 
     * @param evt 
     */
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if (this.fch.showOpenDialog(padre) == JFileChooser.APPROVE_OPTION) {
            this.jLabel1.setText(this.fch.getSelectedFile().getAbsolutePath());
            this.btnDestino.setEnabled(true);
        } else {
        }
    }//GEN-LAST:event_jLabel1MouseClicked
    
    /**
     * Depliega el selector de archivos 
     * @param evt 
     */
    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        if (this.fch.showOpenDialog(padre) == JFileChooser.APPROVE_OPTION) {
            this.jLabel2.setText(this.fch.getSelectedFile().getAbsolutePath());
            this.btnRuta.setEnabled(true);
        } else {
            
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * Lee un archivo y guarda los destinos
     * @param URL 
     */
//    public void cargarDestino(String URL) {
//        File f;
//        String l, csv[];
//        BufferedReader br = null;
//
//        try {
//            br = new BufferedReader(new InputStreamReader(new FileInputStream(new File(URL)), Charset.forName("UTF-8")));
//            while ((l = br.readLine()) != null) {
//                csv = l.split(",");
//                m.agregarDestino(Integer.valueOf(csv[0]), csv[1]);
//            }
//        } catch (FileNotFoundException ex) {
//            JOptionPane.showMessageDialog(padre, "Archivo no encontrado", "Error", JOptionPane.WARNING_MESSAGE);
//        } catch (IOException | NumberFormatException ex) {
//            JOptionPane.showMessageDialog(padre, "Ocurrió un error al leer el archivo. Por favor verifique su sintaxis.", "Error", JOptionPane.ERROR_MESSAGE);
//        }finally {
//            try {
//                if (br != null) {
//                    br.close();
//                }
//            } catch (IOException ex) {
//            }
//        }
//
//    }
    
    /**
     * Lee un archivo y guarda las rutas
     * @param URL 
     */
//    public void cargarRuta(String URL) {
//        String l, csv[];
//        BufferedReader br = null;
//        try {
//            br = new BufferedReader(new InputStreamReader(new FileInputStream(new File(URL)), Charset.forName("UTF-8")));//new FileReader(new File(URL)));
//            while ((l = br.readLine()) != null) {
//                csv = l.split(",");
//                m.agregarRuta(Integer.valueOf(csv[0]), Integer.valueOf(csv[1]), new Ruta(Float.valueOf(csv[2]), Float.valueOf(csv[3]), csv[4]));
//                m.agregarRuta(Integer.valueOf(csv[1]), Integer.valueOf(csv[0]), new Ruta(Float.valueOf(csv[2]), Float.valueOf(csv[3]), csv[4]));
//            }
//        } catch (FileNotFoundException ex) {
//            JOptionPane.showMessageDialog(padre, "Archivo no encontrado", "Error", JOptionPane.WARNING_MESSAGE);
//        } catch (IOException | NumberFormatException ex) {
//            JOptionPane.showMessageDialog(padre, "Ocurrió un error al leer el archivo. Por favor verifique su sintaxis.", "Error", JOptionPane.ERROR_MESSAGE);
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(padre, ex.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
//        }finally {
//            try {
//                if (br != null) {
//                    br.close();
//                }
//            } catch (IOException ex) {
//            }
//        }
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDestino;
    private javax.swing.JButton btnRuta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
